version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    user: "1002"
    volumes:
      - /opt/elasticsearch/configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/elasticsearch/configs/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - /opt/elasticsearch/data/:/usr/share/elasticsearch/data
      - /opt/elasticsearch/logs/:/usr/share/elasticsearch/logs
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: data-elastic

